### ISSUE TITLE
Firefox alatt nem működik

### ISSUE THREAD

**Issue by hajosattila** [Victoare/ncore-makeup#3]
Szia!
Hasznos kis scriptnek tűnik, de sajnos Firefox alatt jelenleg nem működik.

**Comment by Victoare** [comment]
Halli
Firefox 106.0.1 + TamperMonkey 4.18.0-val próbáltam és úgy működik.
Ha valami mást használsz akkor írd le részletesebben, hogy meg tudjuk nézni.

**Comment by hajosattila** [comment]
> Halli Firefox 106.0.1 + TamperMonkey 4.18.0-val próbáltam és úgy működik. Ha valami mást használsz akkor írd le részletesebben, hogy meg tudjuk nézni.

Firefox 106.0.1 + Greasemonkey 4.11
Arch Linux (Sway WM)

Koszonom, hogy foglalkozol vele! :)

**Comment by Victoare** [comment]
Ha minden igaz akkor megjavult (nálam most megy greasemonkey-el), viszont lehet, hogy törölni kell és újra felrakni a scriptet, mert úgy olvastam, hogy a GM nem foglalkozik installálás után a @require metával.

**Comment by hajosattila** [comment]
Működik, és meg törölni/újra felrakni sem kellett! :)
Köszi!

**Comment by Victoare** [comment]
Örülök :)
